# Generated by Django 5.0.2 on 2024-02-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_algo", "0002_transaction_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ask",
            name="filled_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="bid",
            name="filled_quantity",
            field=models.IntegerField(default=0),
        ),
    ]
