# Generated by Django 5.0.2 on 2024-02-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trading_algo", "0004_remove_ask_filled_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                blank=True,
                choices=[("Bought", "Bought"), ("Sold", "Sold")],
                max_length=6,
                null=True,
            ),
        ),
    ]
