# Generated by Django 5.0.2 on 2024-02-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("BID", "Bid"), ("ASK", "Ask")], max_length=3
            ),
        ),
    ]
