# Generated by Django 5.0.2 on 2024-02-14 17:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_orderbook"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pricehistory",
            options={"ordering": ["-date"]},
        ),
    ]
